
    create table tb_employee (
       id int8 generated by default as identity,
        cellphone varchar(255),
        email varchar(255),
        name varchar(255),
        phone_table boolean,
        wtzp boolean,
        phone_id int8,
        sector_id int8,
        primary key (id)
    );

    create table tb_localization (
       id int8 generated by default as identity,
        adress varchar(255),
        city varchar(255),
        floor varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table tb_phone (
       id int8 generated by default as identity,
        phone varchar(255),
        primary key (id)
    );

    create table tb_sector (
       id int8 generated by default as identity,
        name varchar(255),
        local_id int8,
        primary key (id)
    );

    alter table if exists tb_employee 
       add constraint FKattfsjhji6cg87mhvmrovdcwh 
       foreign key (phone_id) 
       references tb_phone;

    alter table if exists tb_employee 
       add constraint FK9qrnqeivwequfs9aoad226r9g 
       foreign key (sector_id) 
       references tb_sector;

    alter table if exists tb_sector 
       add constraint FKpprlusc624mn320pap1s1utlu 
       foreign key (local_id) 
       references tb_localization;
INSERT INTO tb_phone (phone) VALUES ('3219-9173');
INSERT INTO tb_phone (phone) VALUES ('3219-9081');
INSERT INTO tb_phone (phone) VALUES ('3321-4433');
INSERT INTO tb_phone (phone) VALUES ('3321-5544');
INSERT INTO tb_phone (phone) VALUES ('3321-6655');
INSERT INTO tb_phone (phone) VALUES ('3321-7766');
INSERT INTO tb_phone (phone) VALUES ('3321-8877');
INSERT INTO tb_phone (phone) VALUES ('3321-4488');
INSERT INTO tb_phone (phone) VALUES ('3321-9786');
INSERT INTO tb_phone (phone) VALUES ('3321-5678');
INSERT INTO tb_phone (phone) VALUES ('3321-5643');
INSERT INTO tb_phone (phone) VALUES ('3321-0988');
INSERT INTO tb_localization (adress, city, type, floor) VALUES ('Av. Carlos Cunha s/n Calhau', 'São Luis', 'Sede', '2o Piso');
INSERT INTO tb_localization (adress, city, type, floor) VALUES ('Rua Urbano Santos, 160 - Centro', 'Imperatriz', 'Agência', 'Térreo');
INSERT INTO tb_sector (name, local_id) VALUES ('COTEC - DEV', 1);
INSERT INTO tb_sector (name, local_id) VALUES ('COTEC - BD', 2);
INSERT INTO tb_sector (name, local_id) VALUES ('COTEC - INFRA', 2);
INSERT INTO tb_sector (name, local_id) VALUES ('COTEC - NOVO', 2);
INSERT INTO tb_employee (name, email, wtzp, phone_table, phone_id, sector_id) VALUES ('Marcelo Rubim', 'joao.junior@sefaz.ma.gov.br', false, true, 2, 1);
INSERT INTO tb_employee (name, email, wtzp, phone_table, phone_id, sector_id) VALUES ('João Silva Ribeiro Junior', 'joao.junior@sefaz.ma.gov.br', true, true, 3, 1);
INSERT INTO tb_employee (name, email, wtzp, phone_table, phone_id, sector_id) VALUES ('João Ribeiro Junior', 'joao.junior@sefaz.ma.gov.br', false, true, 4, 1);
INSERT INTO tb_employee (name, email, wtzp, phone_table, phone_id, sector_id) VALUES ('João Ribeiro Junior', 'joao.junior@sefaz.ma.gov.br', false, true, 4, 3);
INSERT INTO tb_employee (name, email, wtzp, phone_table, phone_id, sector_id) VALUES ('Humberto Silva', 'joao.junior@sefaz.ma.gov.br', true, true, 5, 3);
INSERT INTO tb_employee (name, email, wtzp, phone_table, phone_id, sector_id) VALUES ('Silva Ribeiro Junior', 'joao.junior@sefaz.ma.gov.br', true, true, 5, 1);
INSERT INTO tb_employee (name, email, wtzp, phone_table, phone_id, sector_id) VALUES ('Humberto Ribeiro Junior', 'joao.junior@sefaz.ma.gov.br', true, true, 2, 1);
INSERT INTO tb_employee (name, email, wtzp, phone_table, phone_id, sector_id) VALUES ('João Silva Junior', 'joao.junior@sefaz.ma.gov.br', true, true, 1, 1);
INSERT INTO tb_employee (name, email, wtzp, phone_table, phone_id, sector_id) VALUES ('João Silva Ribeiro', 'joao.junior@sefaz.ma.gov.br', true, false, 1, 2);
INSERT INTO tb_employee (name, email, wtzp, phone_table, phone_id, sector_id) VALUES ('João Humberto Junior', 'joao.junior@sefaz.ma.gov.br', true, true, 1, 2);
