INSERT INTO tb_phone (phone) VALUES ('3321-4455');
INSERT INTO tb_phone (phone) VALUES ('3321-3344');
INSERT INTO tb_phone (phone) VALUES ('3321-4433');
INSERT INTO tb_phone (phone) VALUES ('3321-5544');
INSERT INTO tb_phone (phone) VALUES ('3321-6655');
INSERT INTO tb_phone (phone) VALUES ('3321-7766');
INSERT INTO tb_phone (phone) VALUES ('3321-8877');
INSERT INTO tb_phone (phone) VALUES ('3321-4488');
INSERT INTO tb_phone (phone) VALUES ('3321-9786');
INSERT INTO tb_phone (phone) VALUES ('3321-5678');
INSERT INTO tb_phone (phone) VALUES ('3321-5643');
INSERT INTO tb_phone (phone) VALUES ('3321-0988');
INSERT INTO tb_localization (adress, city, type) VALUES ('Rua Eupripedes, n 7', 'São Luis', 'Sede');
INSERT INTO tb_localization (adress, city, type) VALUES ('Rua Eupripedes, n 7', 'São Luis', 'Agência');
INSERT INTO tb_localization (adress, city, type) VALUES ('Rua Eupripedes, n 7', 'São Luis', 'Posto');
INSERT INTO tb_localization (adress, city, type) VALUES ('Rua Eupripedes, n 7', 'São Luis', 'Sede');
INSERT INTO tb_sector (name, local_id) VALUES ('COTEC - DEV', 1);
INSERT INTO tb_sector (name, local_id) VALUES ('COTEC - BD', 2);
INSERT INTO tb_sector (name, local_id) VALUES ('COTEC - INFRA', 3);
INSERT INTO tb_employee (name, email, wtzp, phone_table, phone_id, sector_id) VALUES ('Humberto Silva Ribeiro Junior', 'joao.junior@sefaz.ma.gov.br', false, true, 2, 1);
INSERT INTO tb_employee (name, email, wtzp, phone_table, phone_id, sector_id) VALUES ('João Silva Ribeiro Junior', 'joao.junior@sefaz.ma.gov.br', true, true, 3, 1);
INSERT INTO tb_employee (name, email, wtzp, phone_table, phone_id, sector_id) VALUES ('João Ribeiro Junior', 'joao.junior@sefaz.ma.gov.br', false, true, 4, 1);
INSERT INTO tb_employee (name, email, wtzp, phone_table, phone_id, sector_id) VALUES ('João Ribeiro Junior', 'joao.junior@sefaz.ma.gov.br', false, true, 4, 3);
INSERT INTO tb_employee (name, email, wtzp, phone_table, phone_id, sector_id) VALUES ('Humberto Silva', 'joao.junior@sefaz.ma.gov.br', true, true, 5, 3);
INSERT INTO tb_employee (name, email, wtzp, phone_table, phone_id, sector_id) VALUES ('Silva Ribeiro Junior', 'joao.junior@sefaz.ma.gov.br', true, true, 5, 1);
INSERT INTO tb_employee (name, email, wtzp, phone_table, phone_id, sector_id) VALUES ('Humberto Ribeiro Junior', 'joao.junior@sefaz.ma.gov.br', true, true, 2, 1);
INSERT INTO tb_employee (name, email, wtzp, phone_table, phone_id, sector_id) VALUES ('João Silva Junior', 'joao.junior@sefaz.ma.gov.br', true, true, 1, 1);
INSERT INTO tb_employee (name, email, wtzp, phone_table, phone_id, sector_id) VALUES ('João Silva Ribeiro', 'joao.junior@sefaz.ma.gov.br', true, false, 1, 2);
INSERT INTO tb_employee (name, email, wtzp, phone_table, phone_id, sector_id) VALUES ('João Humberto Junior', 'joao.junior@sefaz.ma.gov.br', true, true, 1, 2);
